/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.hna.gui;

import java.util.Date;
import javax.swing.JOptionPane;
import vn.hna.entity.Users;
import vn.hna.util.DateTools;

/**
 *
 * @author Edison
 */
public class FrmMain extends javax.swing.JFrame {
    String fullName = "";
    DateTools dt = new DateTools();

    /**
     * Creates new form FrmAdmin
     */
    public FrmMain() {
        initComponents();
        
        this.setTitle("Crime File System [Admin]");
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        PnlHome pnlHome = new PnlHome();
        pnlMain.add(pnlHome);
        
        for (Users user : FrmLogin.list) {
            fullName = user.getFullName();
        }
        lblFullName.setText("Welcome to " + fullName + " [" + FrmLogin.roleName + "]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        btnRole = new javax.swing.JButton();
        btnCrimeType = new javax.swing.JButton();
        btnArea = new javax.swing.JButton();
        btnCrimeType1 = new javax.swing.JButton();
        btnCriminal = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnFIR = new javax.swing.JButton();
        btnComplaint = new javax.swing.JButton();
        btnCriminal1 = new javax.swing.JButton();
        btnCase = new javax.swing.JButton();
        btnCase1 = new javax.swing.JButton();
        btnPostmortem = new javax.swing.JButton();
        btnPostmortem1 = new javax.swing.JButton();
        btnPostmortem2 = new javax.swing.JButton();
        lblFullName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/hna/img/Header.jpg"))); // NOI18N
        jPanel1.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 620, 420));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHome);

        btnRole.setBackground(new java.awt.Color(255, 255, 255));
        btnRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRole.setText("Roles");
        btnRole.setFocusable(false);
        btnRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRole.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRole);

        btnCrimeType.setBackground(new java.awt.Color(255, 255, 255));
        btnCrimeType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrimeType.setText("Crime Types");
        btnCrimeType.setFocusable(false);
        btnCrimeType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrimeType.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrimeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimeTypeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCrimeType);

        btnArea.setBackground(new java.awt.Color(255, 255, 255));
        btnArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnArea.setText("Areas");
        btnArea.setFocusable(false);
        btnArea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnArea);

        btnCrimeType1.setBackground(new java.awt.Color(255, 255, 255));
        btnCrimeType1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrimeType1.setText("Complaint Types");
        btnCrimeType1.setFocusable(false);
        btnCrimeType1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrimeType1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrimeType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimeType1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCrimeType1);

        btnCriminal.setBackground(new java.awt.Color(255, 255, 255));
        btnCriminal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCriminal.setText("Criminals");
        btnCriminal.setFocusable(false);
        btnCriminal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCriminal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriminalActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCriminal);

        btnUser.setBackground(new java.awt.Color(255, 255, 255));
        btnUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUser.setText("Users");
        btnUser.setFocusable(false);
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUser);

        btnFIR.setBackground(new java.awt.Color(255, 255, 255));
        btnFIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFIR.setText("FIRs");
        btnFIR.setFocusable(false);
        btnFIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFIR.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFIRActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFIR);

        btnComplaint.setBackground(new java.awt.Color(255, 255, 255));
        btnComplaint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnComplaint.setText("Complaints");
        btnComplaint.setFocusable(false);
        btnComplaint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComplaint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });
        jToolBar1.add(btnComplaint);

        btnCriminal1.setBackground(new java.awt.Color(255, 255, 255));
        btnCriminal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCriminal1.setText("Complainants");
        btnCriminal1.setFocusable(false);
        btnCriminal1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCriminal1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCriminal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriminal1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCriminal1);

        btnCase.setBackground(new java.awt.Color(255, 255, 255));
        btnCase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCase.setText("Case Records");
        btnCase.setFocusable(false);
        btnCase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCase);

        btnCase1.setBackground(new java.awt.Color(255, 255, 255));
        btnCase1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCase1.setText("Victim");
        btnCase1.setFocusable(false);
        btnCase1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCase1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCase1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCase1);

        btnPostmortem.setBackground(new java.awt.Color(255, 255, 255));
        btnPostmortem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPostmortem.setText("Postmortems");
        btnPostmortem.setFocusable(false);
        btnPostmortem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPostmortem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPostmortem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostmortemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPostmortem);

        btnPostmortem1.setBackground(new java.awt.Color(255, 255, 255));
        btnPostmortem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPostmortem1.setText("Prisons");
        btnPostmortem1.setFocusable(false);
        btnPostmortem1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPostmortem1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPostmortem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostmortem1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPostmortem1);

        btnPostmortem2.setBackground(new java.awt.Color(255, 255, 255));
        btnPostmortem2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPostmortem2.setText("Prisoners");
        btnPostmortem2.setFocusable(false);
        btnPostmortem2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPostmortem2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPostmortem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostmortem2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPostmortem2);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, 460));

        lblFullName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(102, 0, 102));
        lblFullName.setText("Welcome to ");
        jPanel1.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jMenu1.setText("File");

        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogout);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int conf = JOptionPane.showConfirmDialog(this, "Are you sure to leave?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (conf == JOptionPane.YES_OPTION) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        int conf = JOptionPane.showConfirmDialog(this, "Are you sure to leave?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (conf == JOptionPane.YES_OPTION) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        int conf = JOptionPane.showConfirmDialog(this, "Are you sure to leave?", "Message", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (conf == JOptionPane.YES_OPTION) {
            FrmLogin frmLogin = new FrmLogin();
            this.dispose();
            frmLogin.setVisible(true);
        }
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        PnlHome p = new PnlHome();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnFIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFIRActionPerformed
        PnlFIR p = new PnlFIR();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnFIRActionPerformed

    private void btnRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoleActionPerformed
        PnlRole p = new PnlRole();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnRoleActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        PnlUser p = new PnlUser();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        PnlComplaint p = new PnlComplaint();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnComplaintActionPerformed

    private void btnCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriminalActionPerformed
        PnlCriminal p = new PnlCriminal();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnCriminalActionPerformed

    private void btnCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaseActionPerformed
        PnlCaseRecord p = new PnlCaseRecord();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnCaseActionPerformed

    private void btnPostmortemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostmortemActionPerformed
        PnlPostmortem p = new PnlPostmortem();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnPostmortemActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        PnlArea p = new PnlArea();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnCrimeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimeTypeActionPerformed
        PnlCrimeType p = new PnlCrimeType();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnCrimeTypeActionPerformed

    private void btnCrimeType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimeType1ActionPerformed
        PnlComplaintType p = new PnlComplaintType();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnCrimeType1ActionPerformed

    private void btnCriminal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriminal1ActionPerformed
        PnlComplainant p = new PnlComplainant();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnCriminal1ActionPerformed

    private void btnCase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCase1ActionPerformed
        PnlVictim p = new PnlVictim();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnCase1ActionPerformed

    private void btnPostmortem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostmortem1ActionPerformed
        PnlPrison p = new PnlPrison();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnPostmortem1ActionPerformed

    private void btnPostmortem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostmortem2ActionPerformed
        PnlPrisoner p = new PnlPrisoner();
        pnlMain.removeAll();
        pnlMain.add(p);
        pnlMain.updateUI();
    }//GEN-LAST:event_btnPostmortem2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmMain().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCase;
    private javax.swing.JButton btnCase1;
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnCrimeType;
    private javax.swing.JButton btnCrimeType1;
    private javax.swing.JButton btnCriminal;
    private javax.swing.JButton btnCriminal1;
    private javax.swing.JButton btnFIR;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPostmortem;
    private javax.swing.JButton btnPostmortem1;
    private javax.swing.JButton btnPostmortem2;
    private javax.swing.JButton btnRole;
    private javax.swing.JButton btnUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
